services:
  pharma-ease-frontend:
    image: ${DOCKERHUB_USERNAME}/pharma-ease-frontend:${IMAGE_TAG-latest}
    container_name: pharma-ease-frontend-prod
    restart: unless-stopped
    env_file: 
      - ./.env
    ports:
      - "80:8080"
    networks:
      - prisma-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  prisma-network:
    external: true
