services:
  pharma-ease-frontend:
    image: isyawal16/pharma-ease-frontend:early-v.1
    container_name: pharma-ease-frontend-prod
    restart: unless-stopped
    ports:
      - "80:8080"
    networks:
      - prisma-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  prisma-network:
    external: true
