name: frontend CI pipeline
on: 
  push: 
    branches: 
    - main
    - staging
    - production
  pull_request:
    branches: 
    - main
    - staging

jobs: 
  code-lint:
    runs-on: ubuntu-latest
    steps: 
      - name: 
        uses: 
      - name: 
        uses:
      - name: 
        uses:

  code-scan-and-review: 
    runs-on: ubuntu-latest
    steps: 
      - name: 
        uses: 
      - name: 
        uses:
      - name: 
        uses:
  
  code-test:
    runs-on: ubuntu-latest
    steps:  
      - name: 
        uses: 
      - name: 
        uses:
      - name: 
        uses:
