name: Production and Release CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
      - 'production'
    tags:
      - 'v*'

jobs:
  call-standard-ci:
    uses: ./.github/workflows/ci-standard.yml

  call-security-gateways:
    needs: call-standard-ci
    uses: ./.github/workflows/ci-security.yml

  call-docker-build-push:
    needs: [call-standard-ci, call-security-gateways]
    uses: ./.github/workflows/ci-docker-push.yml
    with:
      image_name: 'isaliefian/pharma-ease-frontend'
      image_tag: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
